name: clang-format
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, devel ]
    paths:
      - "arangod/**"
      - "client-tools/**"
      - "lib/**"
      - "tests/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files within arangod, client-tools (arangosh), lib, & tests
      - run: git diff --cached --diff-filter=ACMRT --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- arangod/ lib/ client-tools/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$'
      - name: Pipe into file
      - run: git diff --cached --diff-filter=ACMRT --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- arangod/ lib/ client-tools/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$' > CHANGED_FILES      
      - name: run ls
      - run: ls -al
      - name: arangodb-clang-format
        uses: arangodb/clang-format-action@1.0.1
